[schema]
url = "http://localhost:8888"
lang = "Rust"
orm = "Diesel"
root = "src/models"
schema_id = "111e8b5b-2f43-456a-ae83-a079131813bb"
branch = "main"

[tables]
names = ["cluster", "compute_unit"]
