lang = "Rust"
package_type = "executable"

[[links]]
icon = "FaCodeBranch"
internal = true
label = "Pull Requests"
link = "/pulls"

[[links]]
icon = "FaRegPlayCircle"
internal = true
label = "Pipelines"
link = "/actions"

[[links]]
icon = "FaGithub"
internal = true
label = "Browse Repo"
link = ""
