[version]
channel = "Nightly"
major = 0
minor = 0
patch = 0
revision = 0

[[references]]
file_name = "Cargo.toml"
output_type = "String"
variable = "version"

[settings]
git_url_prefix = "https://github.com/ginger-society/template-backend-rust"
