lang = "Rust"
organization_id = "ginger-society"
dir = "."
spec_url = "/openapi.json"
service_type = "RPCEndpoint"

[services."@ginger-society/IAMService"]
stage = "https://api-staging.gingersociety.org/iam"
dev = "http://localhost:8080/iam"
stage_k8 = "http://iam-service-api-service/iam"

[portals_refs]

[ws_refs]

[urls]
stage_k8 = "http://iam-service-api-service/iam"
stage = "https://api-staging.gingersociety.org/iam"
prod = "https://exampleapi.com"
prod_k8 = "https://exampleapi.com"
dev = "http://localhost:8080/iam"
